"""python-tesseron: Python implementation of the Tesseron protocol.

This package provides a clean-room Python implementation of the Tesseron
protocol for typed action exposure to AI agents over MCP/WebSocket.

Protocol version: 1.2.0
Spec reference: SPEC_tesseron_protocol_for_python.md
"""

from python_tesseron.context import ActionContext
from python_tesseron.errors import (
    ActionNotFoundError,
    CancelledError,
    ElicitationNotAvailableError,
    HandlerError,
    InputValidationError,
    InternalError,
    InvalidParamsError,
    InvalidRequestError,
    MethodNotFoundError,
    ParseError,
    ProtocolMismatchError,
    ResumeFailedError,
    SamplingDepthExceededError,
    SamplingNotAvailableError,
    TesseronError,
    TimeoutError,
    TransportClosedError,
    UnauthorizedError,
)
from python_tesseron.manifest import generate_instance_id
from python_tesseron.tesseron import Tesseron
from python_tesseron.types import (
    ActionAnnotations,
    ActionCancelParams,
    ActionInvokeParams,
    ActionManifestEntry,
    ActionProgressParams,
    ActionsListChangedParams,
    AgentIdentity,
    AppMetadata,
    ClaimedParams,
    ElicitationRequestParams,
    ElicitationResult,
    HelloParams,
    InstanceManifest,
    InvocationResult,
    JsonRpcErrorObject,
    JsonRpcErrorResponse,
    JsonRpcNotification,
    JsonRpcRequest,
    JsonRpcSuccessResponse,
    ResourceManifestEntry,
    ResourceReadParams,
    ResourceReadResult,
    ResourcesListChangedParams,
    ResourceSubscribeParams,
    ResourceUnsubscribeParams,
    ResourceUpdatedParams,
    ResumeParams,
    SamplingRequestParams,
    SamplingResult,
    SessionState,
    TesseronCapabilities,
    UdsTransport,
    WelcomeResult,
    WsTransport,
)

__all__ = [
    # Main SDK class
    "Tesseron",
    "ActionContext",
    # Errors
    "TesseronError",
    "ParseError",
    "InvalidRequestError",
    "MethodNotFoundError",
    "InvalidParamsError",
    "InternalError",
    "ProtocolMismatchError",
    "CancelledError",
    "TimeoutError",
    "ActionNotFoundError",
    "InputValidationError",
    "HandlerError",
    "SamplingNotAvailableError",
    "ElicitationNotAvailableError",
    "SamplingDepthExceededError",
    "UnauthorizedError",
    "TransportClosedError",
    "ResumeFailedError",
    # Types
    "TesseronCapabilities",
    "AppMetadata",
    "AgentIdentity",
    "ActionAnnotations",
    "ActionManifestEntry",
    "ResourceManifestEntry",
    "HelloParams",
    "WelcomeResult",
    "ResumeParams",
    "ClaimedParams",
    "ActionInvokeParams",
    "InvocationResult",
    "ActionCancelParams",
    "ActionProgressParams",
    "ActionsListChangedParams",
    "ResourceReadParams",
    "ResourceReadResult",
    "ResourceSubscribeParams",
    "ResourceUnsubscribeParams",
    "ResourceUpdatedParams",
    "ResourcesListChangedParams",
    "SamplingRequestParams",
    "SamplingResult",
    "ElicitationRequestParams",
    "ElicitationResult",
    "JsonRpcRequest",
    "JsonRpcNotification",
    "JsonRpcSuccessResponse",
    "JsonRpcErrorObject",
    "JsonRpcErrorResponse",
    "WsTransport",
    "UdsTransport",
    "InstanceManifest",
    "SessionState",
    # Utilities
    "generate_instance_id",
]
